class TextUtils:
    APP_STARTED = 'App started'
    APP_QUIT = 'App can be stopped using Ctrl + C'
    LISTEN_KEYPRESS_START = 'Listening keypress SPACE to start recording'
    LISTEN_KEYPRESS_STOP = 'Listening keypress ESC to stop keyboard listening'
    LISTEN_HOTWORD_START = 'Listening hotword COMPUTER to start recording'
    LISTEN_HOTWORD_KEYPRESS = 'Listening hotword COMPUTER or keypress SPACE to start recording'
    STOP_LISTEN_KEYPRESS = 'Keyboard listening canceled'
    START_RECORDING_AUDIO = 'Audio recording started'
    STOP_RECORDING_AUDIO = 'Audio recording completed'
    START_ASSISTANT_ANSWER = 'Assistant response'
    START_SPEECH_RECOGNITION = 'Speech is being recognized'
    STOP_SPEECH_RECOGNITION = 'Speech recognition completed {0}'
    SEND_ASSISTANT_QUERY = 'Assistant is being called'
    RECEIVE_ASSISTANT_RESPONSE = 'Assistant response received'
    DOWNLOAD_ASSISTANT_RESPONSE = 'Downloading assistant response'